// ─── Mock Bikes ────────────────────────────────────────────────────────────────
export const MOCK_BIKES = [
  {
    id: 'b1',
    title: 'Giant Defy Advanced 2 2023 — Carbon Endurance Road',
    brand: 'Giant',
    model: 'Defy Advanced 2',
    year: 2023,
    category: 'ROAD',
    frameSize: 54,
    frameMaterial: 'Carbon',
    groupset: 'Shimano 105',
    condition: 'like_new',
    price: 28500000,
    isNegotiable: true,
    location: 'TP. Hồ Chí Minh',
    images: [],
    isVerified: true,
    sellerId: 'u1',
    sellerName: 'Minh Tuấn',
    sellerPhone: '0901234567',
    sellerRating: 4.9,
    sellerReviewCount: 32,
    views: 218,
    createdAt: '2026-04-10',
    description:
      'Xe road carbon Giant Defy Advanced 2 2023, mua mới 100% cuối 2023, chạy được khoảng 2.000km. Khung carbon Advanced-grade nhẹ, hệ thống Shimano 105 12 speed mượt mà. Phù hợp đường trường, touring. Đã kiểm định bởi BikeConnect, đầy đủ phụ kiện kèm theo.',
  },
  {
    id: 'b2',
    title: 'Trek Domane AL 4 Disc 2022 — Aluminium Endurance',
    brand: 'Trek',
    model: 'Domane AL 4',
    year: 2022,
    category: 'ROAD',
    frameSize: 56,
    frameMaterial: 'Aluminum',
    groupset: 'Shimano Tiagra',
    condition: 'good',
    price: 16800000,
    isNegotiable: false,
    location: 'Hà Nội',
    images: [],
    isVerified: true,
    sellerId: 'u2',
    sellerName: 'Hoàng Nam',
    sellerPhone: '0912345678',
    sellerRating: 4.7,
    sellerReviewCount: 14,
    views: 145,
    createdAt: '2026-04-09',
    description:
      'Trek Domane AL 4 Disc 2022 màu xanh navy, phanh đĩa thủy lực Shimano. Xe đi chủ yếu cuối tuần, bảo dưỡng định kỳ, không có vết trầy xước lớn. Lý tưởng cho người mới vào road hoặc commuter dài.',
  },
  {
    id: 'b3',
    title: 'Specialized Rockhopper Comp 29 2023 — MTB XC',
    brand: 'Specialized',
    model: 'Rockhopper Comp 29',
    year: 2023,
    category: 'MTB',
    frameSize: 52,
    frameMaterial: 'Aluminum',
    groupset: 'SRAM NX Eagle',
    condition: 'like_new',
    price: 21000000,
    isNegotiable: true,
    location: 'Đà Nẵng',
    images: [],
    isVerified: false,
    sellerId: 'u3',
    sellerName: 'Thanh Hà',
    sellerPhone: '0923456789',
    sellerRating: 4.5,
    sellerReviewCount: 8,
    views: 97,
    createdAt: '2026-04-08',
    description:
      'Specialized Rockhopper Comp 29" 2023, fork SR Suntour XCM 100mm, SRAM NX Eagle 12 speed. Mua cuối 2023, chạy khoảng 500km đường mòn quanh Đà Nẵng – Bà Nà. Cần bán vì chuyển sang full-sus. Còn bảo hành khung.',
  },
  {
    id: 'b4',
    title: 'Cannondale Topstone Carbon Lefty 3 2022 — Gravel',
    brand: 'Cannondale',
    model: 'Topstone Carbon Lefty 3',
    year: 2022,
    category: 'GRAVEL',
    frameSize: 54,
    frameMaterial: 'Carbon',
    groupset: 'SRAM Rival AXS',
    condition: 'good',
    price: 38000000,
    isNegotiable: true,
    location: 'TP. Hồ Chí Minh',
    images: [],
    isVerified: true,
    sellerId: 'u4',
    sellerName: 'Văn Đức',
    sellerPhone: '0934567890',
    sellerRating: 5.0,
    sellerReviewCount: 27,
    views: 312,
    createdAt: '2026-04-07',
    description:
      'Cannondale Topstone Carbon Lefty 3 2022, hệ truyền động SRAM Rival AXS không dây. Fork Lefty Oliver Carbon độc đáo. Xe gravel đa năng, đi đường nhựa và đường đất đều tốt. Đã qua kiểm định, đầy đủ giấy tờ.',
  },
  {
    id: 'b5',
    title: 'Merida Scultura 4000 2023 — Carbon Road Racing',
    brand: 'Merida',
    model: 'Scultura 4000',
    year: 2023,
    category: 'ROAD',
    frameSize: 50,
    frameMaterial: 'Carbon',
    groupset: 'Shimano 105',
    condition: 'like_new',
    price: 32000000,
    isNegotiable: false,
    location: 'Hà Nội',
    images: [],
    isVerified: false,
    sellerId: 'u5',
    sellerName: 'Quốc Anh',
    sellerPhone: '0945678901',
    sellerRating: 4.8,
    sellerReviewCount: 19,
    views: 174,
    createdAt: '2026-04-06',
    description:
      'Merida Scultura 4000 2023 khung carbon CF4, Shimano 105 R7100 12 speed, phanh đĩa thủy lực. Xe đua nhẹ, khí động học tốt. Mới đi được 1.200km. Còn bảo hành chính hãng 2 năm.',
  },
  {
    id: 'b6',
    title: 'Cube Agree C:62 Pro 2022 — Aero Carbon Road',
    brand: 'Cube',
    model: 'Agree C:62 Pro',
    year: 2022,
    category: 'ROAD',
    frameSize: 58,
    frameMaterial: 'Carbon',
    groupset: 'Shimano Ultegra',
    condition: 'good',
    price: 42000000,
    isNegotiable: true,
    location: 'TP. Hồ Chí Minh',
    images: [],
    isVerified: true,
    sellerId: 'u6',
    sellerName: 'Bảo Trân',
    sellerPhone: '0956789012',
    sellerRating: 4.6,
    sellerReviewCount: 11,
    views: 208,
    createdAt: '2026-04-05',
    description:
      'Cube Agree C:62 Pro 2022, khung carbon aero siêu nhẹ, Shimano Ultegra R8020 di-2 thủy lực. Xe thuộc dạng endurance aero. Còn đẹp, đi khoảng 4.000km. Có thể thương lượng cho người mua nhanh.',
  },
  {
    id: 'b7',
    title: 'Brompton M6L 2023 — Xe Gập 6 Tốc Độ Classic',
    brand: 'Brompton',
    model: 'M6L',
    year: 2023,
    category: 'FOLD',
    frameSize: 0,
    frameMaterial: 'Steel',
    groupset: 'Sturmey-Archer 6 speed',
    condition: 'like_new',
    price: 26500000,
    isNegotiable: false,
    location: 'TP. Hồ Chí Minh',
    images: [],
    isVerified: true,
    sellerId: 'u7',
    sellerName: 'Lan Anh',
    sellerPhone: '0967890123',
    sellerRating: 4.9,
    sellerReviewCount: 41,
    views: 389,
    createdAt: '2026-04-04',
    description:
      'Brompton M6L 2023 màu Flame Lacquer chính hãng, 6 tốc độ, tay lái M-bar. Đã đi khoảng 800km, bảo dưỡng đầy đủ. Đi kèm túi gập và giá đỡ. Lý tưởng đi làm kết hợp xe buýt/tàu điện.',
  },
  {
    id: 'b8',
    title: 'Scott Scale 960 2022 — MTB Hardtail 29"',
    brand: 'Scott',
    model: 'Scale 960',
    year: 2022,
    category: 'MTB',
    frameSize: 50,
    frameMaterial: 'Aluminum',
    groupset: 'Shimano Deore',
    condition: 'good',
    price: 14500000,
    isNegotiable: true,
    location: 'Đà Nẵng',
    images: [],
    isVerified: false,
    sellerId: 'u8',
    sellerName: 'Trọng Khải',
    sellerPhone: '0978901234',
    sellerRating: 4.3,
    sellerReviewCount: 6,
    views: 88,
    createdAt: '2026-04-03',
    description:
      'Scott Scale 960 2022 hardtail 29", fork RockShox Judy Silver 100mm, Shimano Deore 1x12. Xe MTB đầu vào xuất sắc, phù hợp XC và trail nhẹ. Có vài vết xước nhỏ ở gầm nhưng không ảnh hưởng chức năng.',
  },
  {
    id: 'b9',
    title: 'Canyon Grail CF SL 8 2023 — Carbon Gravel Racing',
    brand: 'Canyon',
    model: 'Grail CF SL 8',
    year: 2023,
    category: 'GRAVEL',
    frameSize: 56,
    frameMaterial: 'Carbon',
    groupset: 'SRAM Force AXS',
    condition: 'like_new',
    price: 55000000,
    isNegotiable: true,
    location: 'Hà Nội',
    images: [],
    isVerified: true,
    sellerId: 'u9',
    sellerName: 'Phương Linh',
    sellerPhone: '0989012345',
    sellerRating: 4.8,
    sellerReviewCount: 23,
    views: 267,
    createdAt: '2026-04-02',
    description:
      'Canyon Grail CF SL 8 2023, hệ truyền động SRAM Force AXS 12 speed không dây. Tay lái double-deck VCLS 2.0 hấp thụ rung. Xe gravel đỉnh cao, hầu như mới. Còn bảo hành Canyon.',
  },
  {
    id: 'b10',
    title: 'Pinarello Prince FX Disc 2022 — Carbon Road Italian',
    brand: 'Pinarello',
    model: 'Prince FX Disc',
    year: 2022,
    category: 'ROAD',
    frameSize: 51,
    frameMaterial: 'Carbon',
    groupset: 'Shimano Ultegra Di2',
    condition: 'good',
    price: 68000000,
    isNegotiable: true,
    location: 'TP. Hồ Chí Minh',
    images: [],
    isVerified: true,
    sellerId: 'u10',
    sellerName: 'Hữu Nghĩa',
    sellerPhone: '0990123456',
    sellerRating: 4.9,
    sellerReviewCount: 15,
    views: 455,
    createdAt: '2026-04-01',
    description:
      'Pinarello Prince FX Disc 2022, khung TORAYCA T900 carbon, Shimano Ultegra R8170 Di2 12 speed. Xe đua cao cấp dành cho cyclist nghiêm túc. Đã kiểm định, toàn bộ linh kiện nguyên bản.',
  },
  {
    id: 'b11',
    title: 'Giant Escape 3 2024 — Urban Hybrid Đô Thị',
    brand: 'Giant',
    model: 'Escape 3',
    year: 2024,
    category: 'URBAN',
    frameSize: 48,
    frameMaterial: 'Aluminum',
    groupset: 'Shimano Tourney',
    condition: 'new',
    price: 8500000,
    isNegotiable: false,
    location: 'Hà Nội',
    images: [],
    isVerified: false,
    sellerId: 'u11',
    sellerName: 'Ngọc Huyền',
    sellerPhone: '0901234560',
    sellerRating: 4.4,
    sellerReviewCount: 3,
    views: 56,
    createdAt: '2026-04-11',
    description:
      'Giant Escape 3 2024 mới 100%, màu xanh lá, chưa đăng ký. Xe hybrid đô thị phù hợp đi làm, đi chợ hàng ngày. Nhẹ, dễ điều khiển, có chắn bùn và giá đỡ hành lý.',
  },
  {
    id: 'b12',
    title: 'Trek FX 3 Disc 2023 — Urban Fitness Bike',
    brand: 'Trek',
    model: 'FX 3 Disc',
    year: 2023,
    category: 'URBAN',
    frameSize: 52,
    frameMaterial: 'Aluminum',
    groupset: 'Shimano Deore',
    condition: 'used',
    price: 12000000,
    isNegotiable: true,
    location: 'Đà Nẵng',
    images: [],
    isVerified: false,
    sellerId: 'u12',
    sellerName: 'Tuấn Kiệt',
    sellerPhone: '0912345670',
    sellerRating: 4.2,
    sellerReviewCount: 5,
    views: 73,
    createdAt: '2026-03-30',
    description:
      'Trek FX 3 Disc 2023, Shimano Deore 10 speed, phanh đĩa cơ. Đi hàng ngày khoảng 2 năm, bảo dưỡng định kỳ. Có vài vết trầy nhẹ. Thích hợp commuting và fitness cycling.',
  },
]

// ─── Mock Reviews ──────────────────────────────────────────────────────────────
export const MOCK_REVIEWS = [
  { id: 'r1', bikeId: 'b1', reviewerName: 'Hoàng Minh', rating: 5, comment: 'Xe đúng như mô tả, seller nhiệt tình hỗ trợ. Giao dịch suôn sẻ, rất hài lòng!', createdAt: '2026-03-15' },
  { id: 'r2', bikeId: 'b1', reviewerName: 'Thanh Bình', rating: 4, comment: 'Xe tốt, giá hợp lý. Seller trả lời tin nhắn nhanh. Có thể thương lượng thêm một chút.', createdAt: '2026-03-10' },
  { id: 'r3', bikeId: 'b1', reviewerName: 'Văn Long', rating: 5, comment: 'Chất lượng vượt mong đợi, khung carbon nhẹ, groupset chạy êm. Seller uy tín 10 điểm.', createdAt: '2026-02-28' },
  { id: 'r4', bikeId: 'b2', reviewerName: 'Quỳnh Nga', rating: 4, comment: 'Xe đẹp, đúng mô tả. Seller giao xe tận nơi. Giá ok cho Trek Domane.', createdAt: '2026-03-20' },
  { id: 'r5', bikeId: 'b2', reviewerName: 'Đình Khoa', rating: 5, comment: 'Mua xe đầu tiên trên BikeConnect, trải nghiệm rất tốt. Xe đúng chất lượng, seller chuyên nghiệp.', createdAt: '2026-03-05' },
]

// ─── Mock Conversations ────────────────────────────────────────────────────────
export const MOCK_CONVERSATIONS = [
  {
    id: 'c1',
    otherUserId: 'u1',
    otherUserName: 'Minh Tuấn',
    bikeId: 'b1',
    bikeTitle: 'Giant Defy Advanced 2 2023',
    bikePrice: 28500000,
    lastMessage: 'Xe còn không bạn? Mình quan tâm lắm.',
    lastMessageTime: '10:32',
    unreadCount: 2,
    messages: [
      { id: 'm1', senderId: 'me', text: 'Chào bạn, xe Giant Defy còn không?', time: '10:20' },
      { id: 'm2', senderId: 'u1', text: 'Chào! Xe vẫn còn bạn nhé.', time: '10:25' },
      { id: 'm3', senderId: 'me', text: 'Xe còn không bạn? Mình quan tâm lắm.', time: '10:32' },
      {
        id: 'm4',
        senderId: 'u1',
        type: 'offer',
        offerPrice: 27000000,
        text: 'Mình thấy bạn đã đặt giá 27.000.000₫ cho xe.',
        time: '10:33',
      },
    ],
  },
  {
    id: 'c2',
    otherUserId: 'u4',
    otherUserName: 'Văn Đức',
    bikeId: 'b4',
    bikeTitle: 'Cannondale Topstone Carbon 2022',
    bikePrice: 38000000,
    lastMessage: 'Bạn có thể giảm thêm không?',
    lastMessageTime: 'Hôm qua',
    unreadCount: 0,
    messages: [
      { id: 'm1', senderId: 'u4', text: 'Xin chào! Bạn hỏi về Cannondale Topstone?', time: '09:00' },
      { id: 'm2', senderId: 'me', text: 'Đúng rồi, xe còn không bạn?', time: '09:05' },
      { id: 'm3', senderId: 'u4', text: 'Còn bạn ơi, xe đẹp lắm, đã kiểm định rồi.', time: '09:10' },
      { id: 'm4', senderId: 'me', text: 'Bạn có thể giảm thêm không?', time: '09:15' },
    ],
  },
  {
    id: 'c3',
    otherUserId: 'u7',
    otherUserName: 'Lan Anh',
    bikeId: 'b7',
    bikeTitle: 'Brompton M6L 2023',
    bikePrice: 26500000,
    lastMessage: 'Cảm ơn bạn, mình sẽ suy nghĩ thêm.',
    lastMessageTime: '2 ngày trước',
    unreadCount: 0,
    messages: [
      { id: 'm1', senderId: 'me', text: 'Hi, xe Brompton này còn bao nhiêu tháng bảo hành?', time: '14:00' },
      { id: 'm2', senderId: 'u7', text: 'Còn 18 tháng bảo hành chính hãng bạn nhé!', time: '14:30' },
      { id: 'm3', senderId: 'me', text: 'Cảm ơn bạn, mình sẽ suy nghĩ thêm.', time: '15:00' },
    ],
  },
  {
    id: 'c4',
    otherUserId: 'u9',
    otherUserName: 'Phương Linh',
    bikeId: 'b9',
    bikeTitle: 'Canyon Grail CF SL 8 2023',
    bikePrice: 55000000,
    lastMessage: 'Mình đồng ý giá 53 triệu bạn nhé.',
    lastMessageTime: '3 ngày trước',
    unreadCount: 1,
    messages: [
      { id: 'm1', senderId: 'me', text: 'Xe Canyon Grail này bạn có thể demo trực tiếp không?', time: '08:00' },
      { id: 'm2', senderId: 'u9', text: 'Được bạn, bạn ở đâu để mình sắp xếp nhé?', time: '08:20' },
      { id: 'm3', senderId: 'me', text: 'Mình ở Hà Nội, gần Ba Đình.', time: '08:25' },
      { id: 'm4', senderId: 'u9', text: 'Mình đồng ý giá 53 triệu bạn nhé.', time: '09:00' },
    ],
  },
  {
    id: 'c5',
    otherUserId: 'u2',
    otherUserName: 'Hoàng Nam',
    bikeId: 'b2',
    bikeTitle: 'Trek Domane AL 4 Disc 2022',
    bikePrice: 16800000,
    lastMessage: 'Giá đã fix rồi bạn ơi, không thương lượng thêm.',
    lastMessageTime: '1 tuần trước',
    unreadCount: 0,
    messages: [
      { id: 'm1', senderId: 'me', text: 'Bạn ơi, xe Trek Domane đi bao nhiêu km rồi?', time: '17:00' },
      { id: 'm2', senderId: 'u2', text: 'Khoảng 3.500km bạn nhé, bảo dưỡng đầy đủ.', time: '17:10' },
      { id: 'm3', senderId: 'me', text: 'Giá 16 triệu được không bạn?', time: '17:15' },
      { id: 'm4', senderId: 'u2', text: 'Giá đã fix rồi bạn ơi, không thương lượng thêm.', time: '17:30' },
    ],
  },
]

// ─── Mock Orders ───────────────────────────────────────────────────────────────
export const MOCK_ORDERS = [
  {
    id: 'ORD-001',
    bikeId: 'b2',
    bikeTitle: 'Trek Domane AL 4 Disc 2022',
    counterpartName: 'Hoàng Nam',
    role: 'USER', // Đơn mua
    price: 16800000,
    status: 'COMPLETED',
    createdAt: '2026-03-20',
    deliveryAddress: '123 Đường A, Quận 1, TP.HCM'
  },
  {
    id: 'ORD-002',
    bikeId: 'b7',
    bikeTitle: 'Brompton M6L 2023',
    counterpartName: 'Lan Anh',
    role: 'USER',
    price: 26500000,
    status: 'PENDING_PAYMENT',
    createdAt: '2026-04-16',
    deliveryAddress: 'None'
  },
  {
    id: 'ORD-003',
    bikeId: 'b3',
    bikeTitle: 'Specialized Rockhopper Comp 29 2023',
    counterpartName: 'Thanh Hà',
    role: 'USER',
    price: 21000000,
    status: 'IN_DELIVERY',
    createdAt: '2026-04-14',
    deliveryAddress: '456 Lê Lợi, Đà Nẵng'
  },
  {
    id: 'ORD-004',
    bikeId: 'b4',
    bikeTitle: 'Cannondale Topstone Carbon Lefty 3 2022',
    counterpartName: 'Văn Đức',
    role: 'USER', // Đơn bán
    price: 38000000,
    status: 'DELIVERED',
    createdAt: '2026-04-10',
    deliveryAddress: '789 Nguyễn Văn Linh, Hà Nội'
  },
  {
    id: 'ORD-005',
    bikeId: 'b11',
    bikeTitle: 'Giant Escape 3 2024',
    counterpartName: 'Ngọc Huyền',
    role: 'USER',
    price: 8500000,
    status: 'RETURN_REQUESTED',
    createdAt: '2026-04-12',
    deliveryAddress: 'Khách đổi ý do trầy xước nhẹ'
  },
  {
    id: 'ORD-006',
    bikeId: 'b5',
    bikeTitle: 'Merida Scultura 4000 2023',
    counterpartName: 'Quốc Anh',
    role: 'USER',
    price: 32000000,
    status: 'CANCELLED',
    createdAt: '2026-03-15',
    deliveryAddress: ''
  },
]

// ─── Mock Users (Login) ────────────────────────────────────────────────────────
export const MOCK_USERS = [
  {
    id: 'u1',
    email: 'minhtuan@gmail.com',
    password: '123456',
    fullName: 'Minh Tuấn',
    phone: '0901234567',
    role: 'USER',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: 4.9,
    reviewCount: 32,
    isVerified: true,
    createdAt: '2025-01-10',
  },
  {
    id: 'u2',
    email: 'hoangnam@gmail.com',
    password: '123456',
    fullName: 'Hoàng Nam',
    phone: '0912345678',
    role: 'USER',
    avatar: null,
    location: 'Hà Nội',
    rating: 4.7,
    reviewCount: 14,
    isVerified: true,
    createdAt: '2025-02-15',
  },
  {
    id: 'u3',
    email: 'thanhha@gmail.com',
    password: '123456',
    fullName: 'Thanh Hà',
    phone: '0923456789',
    role: 'USER',
    avatar: null,
    location: 'Đà Nẵng',
    rating: 4.5,
    reviewCount: 8,
    isVerified: false,
    createdAt: '2025-03-01',
  },
  {
    id: 'u4',
    email: 'vanduc@gmail.com',
    password: '123456',
    fullName: 'Văn Đức',
    phone: '0934567890',
    role: 'USER',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: 5.0,
    reviewCount: 27,
    isVerified: true,
    createdAt: '2025-01-20',
  },
  {
    id: 'u5',
    email: 'quocanh@gmail.com',
    password: '123456',
    fullName: 'Quốc Anh',
    phone: '0945678901',
    role: 'USER',
    avatar: null,
    location: 'Hà Nội',
    rating: 4.8,
    reviewCount: 19,
    isVerified: false,
    createdAt: '2025-04-05',
  },
  {
    id: 'u6',
    email: 'baotran@gmail.com',
    password: '123456',
    fullName: 'Bảo Trân',
    phone: '0956789012',
    role: 'USER',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: 4.6,
    reviewCount: 11,
    isVerified: true,
    createdAt: '2025-05-12',
  },
  {
    id: 'u7',
    email: 'lananh@gmail.com',
    password: '123456',
    fullName: 'Lan Anh',
    phone: '0967890123',
    role: 'USER',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: 4.9,
    reviewCount: 41,
    isVerified: true,
    createdAt: '2024-12-01',
  },
  {
    id: 'u8',
    email: 'trongkhai@gmail.com',
    password: '123456',
    fullName: 'Trọng Khải',
    phone: '0978901234',
    role: 'USER',
    avatar: null,
    location: 'Đà Nẵng',
    rating: 4.3,
    reviewCount: 6,
    isVerified: false,
    createdAt: '2025-06-20',
  },
  {
    id: 'u9',
    email: 'phuonglinh@gmail.com',
    password: '123456',
    fullName: 'Phương Linh',
    phone: '0989012345',
    role: 'USER',
    avatar: null,
    location: 'Hà Nội',
    rating: 4.8,
    reviewCount: 23,
    isVerified: true,
    createdAt: '2025-02-28',
  },
  {
    id: 'u10',
    email: 'huunghia@gmail.com',
    password: '123456',
    fullName: 'Hữu Nghĩa',
    phone: '0990123456',
    role: 'USER',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: 4.9,
    reviewCount: 15,
    isVerified: true,
    createdAt: '2025-03-10',
  },
  {
    id: 'u11',
    email: 'ngochuyen@gmail.com',
    password: '123456',
    fullName: 'Ngọc Huyền',
    phone: '0901234560',
    role: 'USER',
    avatar: null,
    location: 'Hà Nội',
    rating: 4.4,
    reviewCount: 3,
    isVerified: false,
    createdAt: '2025-07-01',
  },
  {
    id: 'u12',
    email: 'tuankiet@gmail.com',
    password: '123456',
    fullName: 'Tuấn Kiệt',
    phone: '0912345670',
    role: 'USER',
    avatar: null,
    location: 'Đà Nẵng',
    rating: 4.2,
    reviewCount: 5,
    isVerified: false,
    createdAt: '2025-08-15',
  },
  {
    id: 'admin1',
    email: 'admin@cyclemart.vn',
    password: 'admin123',
    fullName: 'Admin CycleMart',
    phone: '0800000001',
    role: 'ADMIN',
    avatar: null,
    location: 'TP. Hồ Chí Minh',
    rating: null,
    reviewCount: 0,
    isVerified: true,
    createdAt: '2024-01-01',
  },
  {
    id: 'buyer1',
    email: 'buyer@gmail.com',
    password: '123456',
    fullName: 'Nguyễn Mua Hàng',
    phone: '0800000002',
    role: 'USER',
    avatar: null,
    location: 'Hà Nội',
    rating: null,
    reviewCount: 0,
    isVerified: false,
    createdAt: '2025-09-01',
  },
]

// ─── Mock My Listings ──────────────────────────────────────────────────────────
export const MOCK_MY_LISTINGS = [
  {
    id: 'ml1',
    title: 'Giant Defy Advanced 2 2023 — Carbon Endurance Road',
    brand: 'Giant',
    price: 28500000,
    category: 'ROAD',
    condition: 'like_new',
    status: 'ACTIVE',
    views: 218,
    createdAt: '2026-04-10',
    rejectedReason: null,
  },
  {
    id: 'ml2',
    title: 'Trek FX 3 Disc 2023 — Fitness Hybrid',
    brand: 'Trek',
    price: 12000000,
    category: 'URBAN',
    condition: 'good',
    status: 'PENDING_REVIEW',
    views: 0,
    createdAt: '2026-04-12',
    rejectedReason: null,
  },
  {
    id: 'ml3',
    title: 'Bianchi Via Nirone 7 2021 — Road Aluminum',
    brand: 'Bianchi',
    price: 18500000,
    category: 'ROAD',
    condition: 'used',
    status: 'DRAFT',
    views: 0,
    createdAt: '2026-04-14',
    rejectedReason: null,
  },
  {
    id: 'ml4',
    title: 'Specialized Sirrus X 4.0 2022 — Urban Adventure',
    brand: 'Specialized',
    price: 22000000,
    category: 'URBAN',
    condition: 'like_new',
    status: 'SOLD',
    views: 134,
    createdAt: '2026-03-01',
    rejectedReason: null,
  },
  {
    id: 'ml5',
    title: 'Xe đạp không rõ nguồn gốc 2020',
    brand: 'Unknown',
    price: 5000000,
    category: 'URBAN',
    condition: 'used',
    status: 'REJECTED',
    views: 0,
    createdAt: '2026-03-20',
    rejectedReason: 'Không đủ thông tin về nguồn gốc xe, thiếu giấy tờ chứng minh.',
  },
  {
    id: 'ml6',
    title: 'Canyon Endurace CF SL 8 2023 — Carbon Endurance',
    brand: 'Canyon',
    price: 45000000,
    category: 'ROAD',
    condition: 'like_new',
    status: 'ACTIVE',
    views: 89,
    createdAt: '2026-04-03',
    rejectedReason: null,
  },
]

// ─── Mock Inspection Requests ──────────────────────────────────────────────────
export const MOCK_INSPECTION_REQUESTS = [
  {
    id: 'ins1',
    listingId: 'ml1',
    listingTitle: 'Giant Defy Advanced 2 2023 — Carbon Endurance Road',
    address: '123 Nguyễn Huệ, Quận 1, TP. Hồ Chí Minh',
    scheduledDate: '2026-04-20',
    note: 'Nhà có cầu thang, xin lưu ý khi mang thiết bị lên.',
    fee: 250000,
    status: 'ASSIGNED',
    inspectorName: 'Trần Văn Minh',
    inspectorPhone: '0911222333',
    createdAt: '2026-04-17',
    result: null,
    resultNote: null,
  },
  {
    id: 'ins2',
    listingId: 'ml6',
    listingTitle: 'Canyon Endurace CF SL 8 2023 — Carbon Endurance',
    address: '456 Lê Lợi, Quận 3, TP. Hồ Chí Minh',
    scheduledDate: '2026-04-10',
    note: '',
    fee: 250000,
    status: 'PASSED',
    inspectorName: 'Nguyễn Thị Lan',
    inspectorPhone: '0922333444',
    createdAt: '2026-04-08',
    result: 'PASSED',
    resultNote: 'Xe đạt tất cả tiêu chí: khung, phanh, truyền động, bánh xe đều tốt. Đề xuất gắn tag Verified.',
  },
]
