export const ROUTES = {
  HOME: '/',
  BROWSE: '/browse',
  BIKE_DETAIL: '/bike/:id',
  SELL: '/sell',
  INSPECTION: '/inspection',
  COMMUNITY: '/community',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  MY_LISTINGS: '/my-listings',
  WISHLIST: '/favorites',
  MESSAGES: '/messages',
  ORDERS: '/orders',
  PAYMENT_SUCCESS: '/payment-success',
  PAYMENT_FAILURE: '/payment-failure',
}
