export const ROUTES = {
  HOME: '/',
  BROWSE: '/browse',
  BIKE_DETAIL: '/bike/:id',
  SELL: '/sell',
  INSPECTION: '/inspection',
  COMMUNITY: '/community',
  LOGIN: '/login',
  REGISTER: '/register',
  PROFILE: '/profile',
  MY_LISTINGS: '/my-listings',
  WISHLIST: '/favorites',
  MESSAGES: '/messages',
  ORDERS: '/orders',
}
